### ISSUE TITLE
Syntax rules don't compile

### ISSUE THREAD

**Issue by kkeri** [astampoulis/makam#111]
Hi, I'm writing my first language using Makam and I loosely follow the first part of the tutorial.
My syntax rules don't compile and I can't figure out what is wrong. Here is the relavant part of my code.

~~~
%use basic_predicates.
%open syntax.

(* abstract syntax *)

expr : type.
intConst : int -> expr.
var : string -> expr.
lam : string -> expr -> expr.
app : expr -> expr -> expr.

env : type.
both : env -> env -> env.
def : string -> expr -> env.

(* concrete syntax *)

expr : syntax expr.
env : syntax env.

`(syntax_rules <<
    expr ->
        intConst { <makam.int_literal> }
      / var      { <makam.ident> }
      / lam      { "fun" <makam.ident> "." <expr> }
      / app      { <expr> <expr> }
      /          { "(" <expr> ")" }

    env ->
        both     { <def> ";" <env> }
      / def      { <makam.ident> "=" <expr> }
>>).

`(syntax.def_toplevel_js expr).
`(syntax.def_toplevel_js env).
~~~

I get the following errors:
~~~
!! Error in <string>:1:97-100:
   Term of type string -> expr -> env,
   whereas expected a type of form syntax env.


!! Error in file ./syntax.makam:22.18-33.1:
   parsing the syntax rules failed


!! Error in file ./syntax.makam:22.3-33.1:
   Error in staged code.
~~~

The error seems to be related to the subrule `def  { <makam.ident> "=" <expr> }`. Athough I don't have a deep understanding of Makam I believe my code is correct. Please help.

P.S: it's not clear if I have to give my own definitions for the cases of `expr` and `env` besides the syntax rules. I get a different error if I omit them.

P.S.2: I installed Makam via npm. My version is 0.7.40.

**Comment by astampoulis** [comment]
Hi @kkeri , thank you for opening the issue.

The error you are getting is actually in the previous line, in the rule `both { <def> ";" <env> }`. The issue is in the use of `def`: it is a constructor of type `env`, whereas what you need is a parser/pretty-printer of type `syntax env`. 

In more detail -- The way I read such a rule, when it comes to parsing, is this -- try parsing with the `def` parser, followed by a `;` token, followed by the `env` parser. If successful, apply the `both` constructor to the intermediate results, yielding a term of type `env`. Pretty-printing is understood similarly, though in the "opposite" direction. Together, they give a `syntax env`, a parser/pretty-printer pair for the `env` type.

So changing the `<def>` to `<env>` will fix the type issue, but the parser will still not work as expected: the parsing algorithm used is simple PEG parsing (recursive descent + memoization), and does not allow left recursion. So you will have to restructure your grammar a little bit. You also have left recursion in the case of `app` for `expr`.

You can have multiple parsers/pretty-printers for the same type, and that is indeed needed to structure the parser/pretty-printer to have the right precedence, avoid left recursion, etc.

Here's how I would define these rules:

```
`(syntax_rules <<
    expr ->
        lam      { "fun" <makam.ident> "." <expr> }
      / app      { <expr_base> <expr> }
      /          { <expr_base> }

    expr_base ->
        intConst { <makam.int_literal> }
      / var      { <makam.ident> }
      /          { "(" <expr> ")" }

    env ->
        both     { <env_def> ";" <env> }
      /          { <env_def> }

    env_def ->
        def      { <makam.ident> "=" <expr> }
>>).

`(syntax.def_toplevel_js expr).
`(syntax.def_toplevel_js env).


isocast {{ x = fun y . y 5 ; foo = fun a. fun b. fun c. (a b) c }} (E: env) ?
```

Let me know if this helps. On my part, I'm making a couple of TODOs based on your report --

- Makam should preserve the location information in such cases, so it at least points you to the right place for similar issues.  
- Documentation for the syntax rules is long overdue :smile:

**Comment by astampoulis** [comment]
Oh, and for your PS -- yes, you do need to declare `env` and `expr` as `syntax` constructors before the rules themselves.

**Comment by kkeri** [comment]
Thank you @astampoulis, it works. My takeaway is that I can only refer to other parser rules in a parser, which sounds obviuos once I realized it.
I'm looking forward to your improvements. I'm new to HOLP and every bit of information is of great help.
