### ISSUE TITLE
Extending syntax.makam leads to error with non-existent variable nil

### ISSUE THREAD

**Issue by bforte** [astampoulis/makam#115]
I very well may be doing something wrong here, but basically I am struggling with extending the syntax theory:

```
%extend syntax.
followed_by: syntax A -> syntax B -> syntax A.
(*inline (followed_by _ _).*)
rule (followed_by P Follow) (apply cons [syntax.captured P, Follow]).
%end.
```

leads to

```
!! Error in file ./src/syntax.makam:7:67-68:
   Variable nil with type syntax.syntax_args (list A -> list A) A does not exist.
```

Interestingly modifying the stdlib itself leads to the same problem.

---

Makam version: 0.7.40

**Comment by bforte** [comment]
This is likely inherent to `rule`, I assumed I could use it uni-directional. In my particular case I can just use `iso` directly.

**Comment by astampoulis** [comment]
Hi!

The error message is not very eloquent unfortunately, but it's trying to say something like this --

I was expecting a list of syntax arguments, capturing another `list A` and yielding a parser/printer of type `list A`, which will be used to create a parser/printer of type `A`.
This requirement comes from `apply cons`, since `cons` takes an argument of type `A` and another of type `list A`, yielding a parser of type `list A`; and overall we need to create a parser of type `A`. We have captured already a parser/printer of type `A` but missing the one for type `list A`.

I don't think that's really what you want to do here. Instead of `apply cons` I think you need `group`, to just do one parser/printer followed by another!

**Comment by bforte** [comment]
Thank you for the reply! Yeah, `group` works (in the meantime I came up with using `(fun x => x)` instead). I think my confusion was mainly due to the lack of familiarity with λProlog and it was kind of late.

I did get my usecase to work, but am now using `extern_def` since escaping into JS allows me to do efficient transformations on the AST. With the plain `syntax` machinery I somehow ended up writing a lot of intermediate parsers that distracted me from my end goal or ended up with poor performance.
