### ISSUE TITLE
HOAS and composition (question)

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#84]
I want to specify the following thing in Makam: https://suhr.github.io/papers/opcalg.html

There's my previous attempt in Prolog (surely incomplete): https://gist.github.com/suhr/b31ae185dcb9ab87cc4208a29f8b2deb

This is my sketch in Makam: https://gist.github.com/suhr/a9bb1ebc517ea22836f5143b9d866181

The problem is, I'm new to HOAS and don't quite know how to specify polymorphic composition and concatenation. I looked at implementation of System F in examples, but it introduces extra terms `polylam` and `polyinst`, which purpose I do not really understand (especially `polyinst`).

I'd like to hear a few advices how to apply HOAS in this context.

**Comment by astampoulis** [comment]
Hi @suhr ,

I'd love to help but I need to understand a bit more about your system first. Do you have documentation for the typing judgment that you are trying to model somewhere? (The link you posted only contains operational semantics from what I can tell, whereas the sketch contains only the typing judgment.)

It could also help to do a call or move this to an email conversation outside of Github Issues, especially since you're new to HOAS. You can find my contact info at [my website](https://astampoulis.github.io/)

**Comment by suhr** [comment]
I sent an email.

**Comment by suhr** [comment]
I created a repo with makam examples: https://github.com/suhr/makam-examples. So far there's only conc and stlc a la Curry, but I'm going to add some more.

Also, there's a primitive syntax highlighting extension for VS Code: https://github.com/suhr/makam-lang

**Comment by astampoulis** [comment]
Thanks for the pointers @suhr, will take a look!
