### ISSUE TITLE
Error in file ./tox.makam, line 3, character 1: Parse error

### ISSUE THREAD

**Issue by suhr** [astampoulis/makam#87]
In the following file:

```
typeof (mkpath (["tox"]) (["IpAddr"])) (join ([(ref (mkpath (["tox"]) (["Ipv4Addr"]))), (ref (mkpath (["tox"]) (["Ipv6Addr"])))])).
typeof (mkpath (["tox"]) (["Ipv4Addr"])) (prod ([(mkpath (["tox"]) (["Ipv4Addr", "0"])), (mkpath (["tox"]) (["Ipv4Addr", "1"]))])).
typeof (mkpath (["tox"]) (["Ipv4Addr", "0"])) (meet ([(val ((value_int 0x02)) integer), (u 1 big_endian)])).
```

Makam could report the lack of support for hexadecimals in a more clear way (by the way, consider supporting hexadecimals).

**Comment by astampoulis** [comment]
Thanks @suhr, hex literals should be easy to add.

Is the value of the integer important for your use case? (e.g. does any logic in your predicates have to do with the integers?) Just asking because in similar situations in the past, when encoding base types in a different language whose value is not important for the predicates, I have used string literals to encode them. The flexible string literal syntax (with `{{ ... }}` or other combinations of `{`, `[`, etc.) might improve readability in those cases.

**Comment by suhr** [comment]
> Is the value of the integer important for your use case?

Yes, I'd like to have some constant evaluation.
