### ISSUE TITLE
When should we use `<-` vs `:-`?

### ISSUE THREAD

**Issue by brendanzab** [astampoulis/makam#90]
The standard library and some of the examples use `<-` in clauses, but the [tutorial uses `:-`](http://astampoulis.github.io/blog/makam-tutorial-01/). It seems like `:-` was added in https://github.com/astampoulis/makam/commit/822a1f0824236384383adbb0dbd2c10d049507c1 - is that now the preferred syntax?

---

As an aside I just want to really thank you for Makam, it's a really neat tool and I've been having a bunch of fun [playing around with it](https://gist.github.com/brendanzab/7a331adae167ef6399c6b762aa943abd). I also really appreciate that you have it published on NPM/Yarn - it makes it super easy to install. Thanks for all your work! 😍 👏 🎉

**Comment by astampoulis** [comment]
Thank you for your kind note, @brendanzab; much appreciated. Glad to hear that you've been enjoying playing with Makam :smile: Thanks for the pointer, will take a look. Feel free to contact me if there's anything I can help with in your explorations!

There is no difference between `<-` and `:-`, and I tend to use `:-` lately; it's up to personal preference. I added the latter one based on ICFP reviews, since it's the standard in Prolog/λProlog dialects and helps with readability for people already familiar with them. I will make a note to change all occurrences in the standard library to keep things consistent.

**Comment by astampoulis** [comment]
Addressed in #92 .

**Comment by brendanzab** [comment]
Thanks so much! Yeah, I had assumed that might be the case! Good to try out new syntaxes though. 😄
